// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpmVOShAiOlnDKDakq1-7mmx_CEHJnuM',
    appId: '1:190380586563:web:166316ec3571f45bedc6f6',
    messagingSenderId: '190380586563',
    projectId: 'cw8-activity',
    authDomain: 'cw8-activity.firebaseapp.com',
    storageBucket: 'cw8-activity.firebasestorage.app',
    measurementId: 'G-3JMJE2W0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgTSX07GwRu4bz14kMGRHMhebEHxRHiwk',
    appId: '1:190380586563:android:bf47b33cb5904b42edc6f6',
    messagingSenderId: '190380586563',
    projectId: 'cw8-activity',
    storageBucket: 'cw8-activity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZqUhsI9AOiB9vmNaackyazU_9s-4VmI',
    appId: '1:190380586563:ios:e2b88ca29abd4587edc6f6',
    messagingSenderId: '190380586563',
    projectId: 'cw8-activity',
    storageBucket: 'cw8-activity.firebasestorage.app',
    iosBundleId: 'com.example.cw08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZqUhsI9AOiB9vmNaackyazU_9s-4VmI',
    appId: '1:190380586563:ios:e2b88ca29abd4587edc6f6',
    messagingSenderId: '190380586563',
    projectId: 'cw8-activity',
    storageBucket: 'cw8-activity.firebasestorage.app',
    iosBundleId: 'com.example.cw08',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpmVOShAiOlnDKDakq1-7mmx_CEHJnuM',
    appId: '1:190380586563:web:d87abdab689cea5eedc6f6',
    messagingSenderId: '190380586563',
    projectId: 'cw8-activity',
    authDomain: 'cw8-activity.firebaseapp.com',
    storageBucket: 'cw8-activity.firebasestorage.app',
    measurementId: 'G-EL8VPNR4ZK',
  );
}
